// GENERATED FILE — do not edit by hand.
// Run `npm run generate:examples` after adding or editing an *.example.ts file in this folder.
// See scripts/generate-example-sources.mjs for why the source text is generated rather than imported.

import { CollapsibleControlledExample } from './collapsible-controlled.example';
import { CollapsibleCustomTriggerExample } from './collapsible-custom-trigger.example';
import { CollapsibleDisabledExample } from './collapsible-disabled.example';
import { CollapsibleFaqExample } from './collapsible-faq.example';
import { CollapsibleFocusOutExample } from './collapsible-focus-out.example';
import { CollapsibleOverviewExample } from './collapsible-overview.example';

/** Source text of this folder's examples, keyed by the example component itself. */
export const COLLAPSIBLE_EXAMPLE_SOURCES: ReadonlyMap<unknown, string> = new Map<unknown, string>([
  [
    CollapsibleControlledExample,
    'import { Component, signal } from \'@angular/core\';\nimport {\n  ButtonComponent,\n  CollapsibleComponent,\n  GogCollapsibleContentDirective,\n} from \'@guildofgleks/ui\';\n\n@Component({\n  selector: \'app-example\',\n  imports: [ButtonComponent, CollapsibleComponent, GogCollapsibleContentDirective],\n  template: `\n    <gog-button (gogClick)="open.set(true)">Open</gog-button>\n    <gog-button (gogClick)="open.set(false)">Close</gog-button>\n\n    <gog-collapsible [(open)]="open">\n      <p gogCollapsibleContent>\n        No gogCollapsibleTrigger anywhere — [open] is driven entirely from outside.\n      </p>\n    </gog-collapsible>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n      max-width: 420px;\n    }\n  `,\n})\nexport class CollapsibleControlledExample {\n  protected readonly open = signal(false);\n}',
  ],
  [
    CollapsibleCustomTriggerExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  CollapsibleComponent,\n  GogCollapsibleTriggerDirective,\n  GogCollapsibleContentDirective,\n  IconComponent,\n} from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [\n    CollapsibleComponent,\n    GogCollapsibleTriggerDirective,\n    GogCollapsibleContentDirective,\n    IconComponent,\n  ],\n  template: `\n    <gog-collapsible [(open)]=\"open\">\n      <div class=\"card-header\" gogCollapsibleTrigger>\n        <span>Order #4471</span>\n        <gog-icon [name]=\"open() ? 'chevron-up' : 'chevron-down'\" />\n      </div>\n      <div gogCollapsibleContent class=\"card-body\">\n        <p>3 items — shipped Aug 4, arriving Aug 6.</p>\n      </div>\n    </gog-collapsible>\n  `,\n  styles: `\n    :host {\n      display: block;\n      max-width: 420px;\n    }\n    .card-header {\n      display: flex;\n      align-items: center;\n      justify-content: space-between;\n      gap: 12px;\n      padding: 12px 14px;\n      border: 1px solid var(--gog-border-color);\n      border-radius: var(--gog-radius);\n      background: var(--gog-surface-color);\n      cursor: pointer;\n    }\n    .card-body {\n      padding: 0 14px;\n    }\n  `,\n})\nexport class CollapsibleCustomTriggerExample {\n  protected readonly open = signal(false);\n}",
  ],
  [
    CollapsibleDisabledExample,
    'import { Component, signal } from \'@angular/core\';\nimport {\n  CollapsibleComponent,\n  GogCollapsibleTriggerDirective,\n  GogCollapsibleContentDirective,\n} from \'@guildofgleks/ui\';\n\n@Component({\n  selector: \'app-example\',\n  imports: [CollapsibleComponent, GogCollapsibleTriggerDirective, GogCollapsibleContentDirective],\n  template: `\n    <gog-collapsible [(open)]="open" [disabled]="true">\n      <button type="button" gogCollapsibleTrigger>Unavailable section</button>\n      <p gogCollapsibleContent>You should never see this — the trigger is inert.</p>\n    </gog-collapsible>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n      max-width: 420px;\n    }\n  `,\n})\nexport class CollapsibleDisabledExample {\n  protected readonly open = signal(false);\n}',
  ],
  [
    CollapsibleFaqExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  CollapsibleComponent,\n  GogCollapsibleTriggerDirective,\n  GogCollapsibleContentDirective,\n} from '@guildofgleks/ui';\n\ninterface FaqItem {\n  id: string;\n  question: string;\n  answer: string;\n  open: boolean;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [CollapsibleComponent, GogCollapsibleTriggerDirective, GogCollapsibleContentDirective],\n  template: `\n    @for (item of faqItems(); track item.id) {\n      <gog-collapsible [open]=\"item.open\" (openChange)=\"setOpen(item.id, $event)\">\n        <button type=\"button\" gogCollapsibleTrigger>{{ item.question }}</button>\n        <p gogCollapsibleContent>{{ item.answer }}</p>\n      </gog-collapsible>\n    }\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n      max-width: 420px;\n    }\n  `,\n})\nexport class CollapsibleFaqExample {\n  protected readonly faqItems = signal<FaqItem[]>([\n    {\n      id: 'shipping',\n      question: 'How long does shipping take?',\n      answer: '2 business days.',\n      open: false,\n    },\n    {\n      id: 'returns',\n      question: 'What is the return policy?',\n      answer: '30 days, free.',\n      open: false,\n    },\n  ]);\n\n  protected setOpen(id: string, open: boolean): void {\n    this.faqItems.update((items) =>\n      items.map((item) => (item.id === id ? { ...item, open } : item)),\n    );\n  }\n}",
  ],
  [
    CollapsibleFocusOutExample,
    'import { Component, signal } from \'@angular/core\';\nimport {\n  ButtonComponent,\n  CollapsibleComponent,\n  GogCollapsibleContentDirective,\n  GogCollapsibleTriggerDirective,\n} from \'@guildofgleks/ui\';\n\n@Component({\n  selector: \'app-example\',\n  imports: [\n    ButtonComponent,\n    CollapsibleComponent,\n    GogCollapsibleTriggerDirective,\n    GogCollapsibleContentDirective,\n  ],\n  template: `\n    <gog-collapsible [(open)]="open" [collapseOnFocusOut]="true">\n      <button type="button" gogCollapsibleTrigger>Filters</button>\n      <div gogCollapsibleContent>\n        <gog-button variant="outline">A focusable control</gog-button>\n      </div>\n    </gog-collapsible>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n      max-width: 420px;\n    }\n  `,\n})\nexport class CollapsibleFocusOutExample {\n  protected readonly open = signal(false);\n}',
  ],
  [
    CollapsibleOverviewExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  CollapsibleComponent,\n  GogCollapsibleTriggerDirective,\n  GogCollapsibleContentDirective,\n} from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [CollapsibleComponent, GogCollapsibleTriggerDirective, GogCollapsibleContentDirective],\n  template: `\n    <gog-collapsible [(open)]=\"open\">\n      <button type=\"button\" gogCollapsibleTrigger>\n        {{ open() ? 'Hide details' : 'Show details' }}\n      </button>\n      <p gogCollapsibleContent>Ships within 2 business days via standard courier.</p>\n    </gog-collapsible>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n      max-width: 420px;\n    }\n  `,\n})\nexport class CollapsibleOverviewExample {\n  protected readonly open = signal(false);\n}",
  ],
]);
