// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const PAGINATOR_EXAMPLES = {
  paginatorConfig: {
    html: '<!-- No inputs beyond its pages: the labels and the select come from the config. -->\n<gog-paginator [(page)]="page" [(pageSize)]="pageSize" [totalRecords]="60" [fullWidth]="false" />',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { PaginatorComponent, provideGogConfig } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  // Usually in app.config.ts; here on the component, so it reaches only its own paginator.\n  providers: [\n    provideGogConfig({\n      labels: {\n        pagination: 'Seitennavigation',\n        previousPage: 'Vorherige Seite',\n        nextPage: 'Nächste Seite',\n        rowsPerPage: 'Zeilen pro Seite',\n        page: (page, isCurrent) => (isCurrent ? `Seite ${page}` : `Gehe zu Seite ${page}`),\n      },\n      paginator: { showPageSizeSelect: true, pageSizeOptions: [5, 25] },\n    }),\n  ],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorConfigExample {\n  protected readonly page = signal(1);\n  protected readonly pageSize = signal(5);\n}",
    css: '',
  },
  paginatorOverview: {
    html: '<gog-paginator [(page)]="page" [totalPages]="12" />\n\n<p>page {{ page() }} of 12</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorOverviewExample {\n  protected readonly page = signal(1);\n}",
    css: '',
  },
  paginatorRanges: {
    html: '<!-- Twenty pages each, starting on page 10: click towards either end. -->\n<div>\n  <span>window (default)</span>\n  <gog-paginator [(page)]="windowPage" [totalPages]="20" [fullWidth]="false" />\n</div>\n<div>\n  <span>window, pinned ends</span>\n  <gog-paginator\n    [(page)]="pinnedPage"\n    [totalPages]="20"\n    showFirstPage\n    showLastPage\n    [fullWidth]="false"\n  />\n</div>\n<div>\n  <span>[visiblePages]="3"</span>\n  <gog-paginator [(page)]="threePage" [totalPages]="20" [visiblePages]="3" [fullWidth]="false" />\n</div>\n<div>\n  <span>ellipsis</span>\n  <gog-paginator\n    [(page)]="ellipsisPage"\n    [totalPages]="20"\n    rangeMode="ellipsis"\n    [fullWidth]="false"\n  />\n</div>\n<div>\n  <span>ellipsis, [siblingCount]="1"</span>\n  <gog-paginator\n    [(page)]="siblingPage"\n    [totalPages]="20"\n    rangeMode="ellipsis"\n    [siblingCount]="1"\n    [fullWidth]="false"\n  />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorRangesExample {\n  protected readonly windowPage = signal(10);\n  protected readonly pinnedPage = signal(10);\n  protected readonly threePage = signal(10);\n  protected readonly ellipsisPage = signal(10);\n  protected readonly siblingPage = signal(10);\n}",
    css: '',
  },
  paginatorRecords: {
    html: '<div>\n  <ol [start]="(page() - 1) * pageSize() + 1">\n    @for (person of visiblePeople(); track person) {\n      <li>{{ person }}</li>\n    }\n  </ol>\n</div>\n<!-- totalRecords: the paginator counts pages from pageSize itself. -->\n<gog-paginator\n  [(page)]="page"\n  [(pageSize)]="pageSize"\n  [totalRecords]="people.length"\n  showPageSizeSelect\n  [pageSizeOptions]="[5, 10, 20]"\n/>\n\n<p>page: {{ page() }} · pageSize: {{ pageSize() }} · totalRecords: {{ people.length }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';\nimport { PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorRecordsExample {\n  protected readonly people = Array.from({ length: 47 }, (_, index) => `Person ${index + 1}`);\n  protected readonly page = signal(1);\n  protected readonly pageSize = signal(5);\n  protected readonly visiblePeople = computed(() => {\n    const start = (this.page() - 1) * this.pageSize();\n    return this.people.slice(start, start + this.pageSize());\n  });\n}",
    css: '',
  },
  paginatorShrink: {
    html: '<div>\n  <gog-button variant="outline" size="sm" (gogClick)="totalPages.set(3)">totalPages = 3</gog-button>\n  <gog-button variant="outline" size="sm" (gogClick)="reset()">Reset to 8 of 8</gog-button>\n</div>\n<!-- A page past the new end is written back through [(page)]. -->\n<gog-paginator [(page)]="page" [totalPages]="totalPages()" [fullWidth]="false" />\n\n<p>page: {{ page() }} · totalPages: {{ totalPages() }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent, PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorShrinkExample {\n  protected readonly page = signal(8);\n  protected readonly totalPages = signal(8);\n\n  protected reset(): void {\n    this.totalPages.set(8);\n    this.page.set(8);\n  }\n}",
    css: '',
  },
  paginatorSizes: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>size: {{ size }}</span>\n    <gog-paginator [size]="size" [totalPages]="5" [page]="3" [fullWidth]="false" />\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { GogSize, PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorSizesExample {\n  protected readonly sizes: GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
    css: '',
  },
  paginatorStates: {
    html: '<!-- The step buttons disable themselves at the edges. -->\n<div>\n  <span>[page]="1"</span>\n  <gog-paginator [totalPages]="5" [page]="1" [fullWidth]="false" />\n</div>\n<div>\n  <span>[page]="3"</span>\n  <gog-paginator [totalPages]="5" [page]="3" [fullWidth]="false" />\n</div>\n<div>\n  <span>[page]="5"</span>\n  <gog-paginator [totalPages]="5" [page]="5" [fullWidth]="false" />\n</div>\n<div>\n  <span>disabled</span>\n  <gog-paginator [totalPages]="5" [page]="3" [fullWidth]="false" disabled />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorStatesExample {}",
    css: '',
  },
  paginatorWidth: {
    html: '<gog-paginator [totalPages]="5" [page]="2" />\n<gog-paginator [totalPages]="5" [page]="2" [fullWidth]="false" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { PaginatorComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [PaginatorComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class PaginatorWidthExample {}",
    css: '',
  },
} as const satisfies Record<string, ExampleSource>;
