// GENERATED FILE — do not edit by hand.
// Run `npm run generate:examples` after adding or editing an *.example.ts file in this folder.
// See scripts/generate-example-sources.mjs for why the source text is generated rather than imported.

import { AccordionControlledExample } from './accordion-controlled.example';
import { AccordionCustomHeaderExample } from './accordion-custom-header.example';
import { AccordionDisabledExample } from './accordion-disabled.example';
import { AccordionHeadingLevelExample } from './accordion-heading-level.example';
import { AccordionLoadingExample } from './accordion-loading.example';
import { AccordionMultiExample } from './accordion-multi.example';
import { AccordionOverviewExample } from './accordion-overview.example';
import { AccordionSizesExample } from './accordion-sizes.example';

/** Source text of this folder's examples, keyed by the example component itself. */
export const ACCORDION_EXAMPLE_SOURCES: ReadonlyMap<unknown, string> = new Map<unknown, string>([
  [
    AccordionControlledExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  AccordionComponent,\n  ButtonComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, ButtonComponent, GogAccordionContentDirective],\n  template: `\n    <gog-button (gogClick)=\"expandAll()\">Expand all</gog-button>\n    <gog-button (gogClick)=\"collapseAll()\">Collapse all</gog-button>\n\n    <gog-accordion [items]=\"multiItems\" [multi]=\"true\" [(openIds)]=\"openIds\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionControlledExample {\n  protected readonly multiItems: BasicItem[] = [\n    { id: 'billing', title: 'Billing', body: 'Update your card or billing address.' },\n    { id: 'notifications', title: 'Notifications', body: 'Choose which emails you receive.' },\n  ];\n  protected readonly openIds = signal<ReadonlySet<string | number>>(new Set());\n\n  protected expandAll(): void {\n    this.openIds.set(new Set(this.multiItems.map((item) => item.id)));\n  }\n\n  protected collapseAll(): void {\n    this.openIds.set(new Set());\n  }\n}",
  ],
  [
    AccordionCustomHeaderExample,
    "import { Component } from '@angular/core';\nimport {\n  AccordionComponent,\n  GogAccordionChevronDirective,\n  GogAccordionContentDirective,\n  GogAccordionHeaderDirective,\n  GogAccordionItem,\n  GogIconName,\n  IconComponent,\n} from '@guildofgleks/ui';\n\ninterface StatusItem extends GogAccordionItem {\n  icon: GogIconName;\n  subtitle: string;\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [\n    AccordionComponent,\n    GogAccordionHeaderDirective,\n    GogAccordionChevronDirective,\n    GogAccordionContentDirective,\n    IconComponent,\n  ],\n  template: `\n    <gog-accordion [items]=\"statusItems\">\n      <ng-template gogAccordionHeader let-item let-open=\"open\">\n        <gog-icon [name]=\"item.icon\" />\n        <span>{{ item.title }}</span>\n        <span>{{ open ? 'Expanded' : item.subtitle }}</span>\n      </ng-template>\n\n      <ng-template gogAccordionChevron let-open=\"open\">\n        <gog-icon [name]=\"open ? 'chevron-up' : 'chevron-down'\" />\n      </ng-template>\n\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionCustomHeaderExample {\n  protected readonly statusItems: StatusItem[] = [\n    {\n      id: 'api',\n      title: 'API',\n      icon: 'success',\n      subtitle: 'All endpoints responding normally',\n      body: 'p99 latency is 118ms across all regions.',\n    },\n    {\n      id: 'database',\n      title: 'Database',\n      icon: 'warning',\n      subtitle: 'Replica lag above threshold',\n      body: 'The eu-west read replica is 4.2s behind primary.',\n    },\n  ];\n}",
  ],
  [
    AccordionDisabledExample,
    "import { Component } from '@angular/core';\nimport {\n  AccordionComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, GogAccordionContentDirective],\n  template: `\n    <gog-accordion [items]=\"items\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionDisabledExample {\n  protected readonly items: BasicItem[] = [\n    {\n      id: 'shipping',\n      title: 'Shipping',\n      body: 'Ships within 2 business days via standard courier.',\n    },\n    { id: 'returns', title: 'Returns', body: 'Free returns within 30 days of delivery.' },\n    {\n      id: 'warranty',\n      title: 'Warranty (unavailable)',\n      body: 'Not offered on this item.',\n      disabled: true,\n    },\n  ];\n}",
  ],
  [
    AccordionHeadingLevelExample,
    "import { Component } from '@angular/core';\nimport {\n  AccordionComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, GogAccordionContentDirective],\n  template: `\n    <gog-accordion [items]=\"items\" [headingLevel]=\"3\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionHeadingLevelExample {\n  protected readonly items: BasicItem[] = [\n    {\n      id: 'shipping',\n      title: 'Shipping',\n      body: 'Ships within 2 business days via standard courier.',\n    },\n    { id: 'returns', title: 'Returns', body: 'Free returns within 30 days of delivery.' },\n  ];\n}",
  ],
  [
    AccordionLoadingExample,
    "import { Component, signal } from '@angular/core';\nimport { AccordionComponent, ButtonComponent, GogAccordionItem } from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, ButtonComponent],\n  template: `\n    <gog-button (gogClick)=\"toggleLoading()\">Toggle loading</gog-button>\n\n    <gog-accordion [items]=\"items\" [loading]=\"isAccordionLoading()\" />\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionLoadingExample {\n  protected readonly isAccordionLoading = signal(false);\n  protected readonly items: BasicItem[] = [\n    {\n      id: 'shipping',\n      title: 'Shipping',\n      body: 'Ships within 2 business days via standard courier.',\n    },\n    { id: 'returns', title: 'Returns', body: 'Free returns within 30 days of delivery.' },\n  ];\n\n  protected toggleLoading(): void {\n    this.isAccordionLoading.update((current) => !current);\n  }\n}",
  ],
  [
    AccordionMultiExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  AccordionComponent,\n  ButtonComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, ButtonComponent, GogAccordionContentDirective],\n  template: `\n    <gog-button (gogClick)=\"toggleMulti()\"> Multi-open: {{ multi() ? 'on' : 'off' }} </gog-button>\n\n    <gog-accordion [items]=\"multiItems\" [multi]=\"multi()\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionMultiExample {\n  protected readonly multi = signal(false);\n  protected readonly multiItems: BasicItem[] = [\n    { id: 'billing', title: 'Billing', body: 'Update your card or billing address.' },\n    { id: 'notifications', title: 'Notifications', body: 'Choose which emails you receive.' },\n  ];\n\n  protected toggleMulti(): void {\n    this.multi.update((current) => !current);\n  }\n}",
  ],
  [
    AccordionOverviewExample,
    "import { Component, signal } from '@angular/core';\nimport {\n  AccordionComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n  GogAccordionToggleEvent,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, GogAccordionContentDirective],\n  template: `\n    <gog-accordion [items]=\"items\" [expandFirst]=\"true\" (gogToggle)=\"onToggle($event)\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n    <p class=\"readout\">{{ lastToggled() }}</p>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 12px;\n    }\n    .readout {\n      margin: 0;\n      color: var(--gog-muted-text-color);\n      font-size: 0.9em;\n    }\n  `,\n})\nexport class AccordionOverviewExample {\n  protected readonly items: BasicItem[] = [\n    {\n      id: 'shipping',\n      title: 'Shipping',\n      body: 'Ships within 2 business days via standard courier.',\n    },\n    { id: 'returns', title: 'Returns', body: 'Free returns within 30 days of delivery.' },\n  ];\n\n  protected readonly lastToggled = signal('No section toggled yet.');\n\n  protected onToggle(event: GogAccordionToggleEvent): void {\n    this.lastToggled.set(`${event.item.title} ${event.open ? 'opened' : 'closed'}`);\n  }\n}",
  ],
  [
    AccordionSizesExample,
    "import { Component } from '@angular/core';\nimport {\n  AccordionComponent,\n  GogAccordionContentDirective,\n  GogAccordionItem,\n  GogSize,\n} from '@guildofgleks/ui';\n\ninterface BasicItem extends GogAccordionItem {\n  body: string;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [AccordionComponent, GogAccordionContentDirective],\n  template: `\n    <gog-accordion [items]=\"sizeDemoItems\" [size]=\"sizeOption\" [expandFirst]=\"true\">\n      <ng-template gogAccordionContent let-item>\n        <p>{{ item.body }}</p>\n      </ng-template>\n    </gog-accordion>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: stretch;\n      gap: 16px;\n    }\n  `,\n})\nexport class AccordionSizesExample {\n  protected readonly sizeDemoItems: BasicItem[] = [\n    { id: 'one', title: 'Sample section', body: 'Sample content for the size comparison.' },\n  ];\n  protected readonly sizeOption: GogSize = 'md';\n}",
  ],
]);
