// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const BUTTON_EXAMPLES = {
  buttonAriaState: {
    html: '<div>\n  <gog-button variant="outline" [ariaPressed]="mirrored()" (gogClick)="toggleMirror()">\n    Mirror layout\n  </gog-button>\n  <gog-button\n    variant="outline"\n    [ariaExpanded]="filtersOpen()"\n    ariaControls="filters-region"\n    ariaHasPopup="dialog"\n    (gogClick)="toggleFilters()"\n  >\n    Filters\n  </gog-button>\n</div>\n\n<!-- aria-controls must name an element that exists, so this hides rather than leaves. -->\n<p id="filters-region" [hidden]="!filtersOpen()">The region the Filters button controls.</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonAriaStateExample {\n  protected readonly mirrored = signal(false);\n  protected readonly filtersOpen = signal(false);\n\n  protected toggleMirror(): void {\n    this.mirrored.update((on) => !on);\n  }\n\n  protected toggleFilters(): void {\n    this.filtersOpen.update((open) => !open);\n  }\n}",
    css: '',
  },
  buttonDebounce: {
    html: '<gog-button variant="primary" [debounce]="300" (gogClick)="count()">Click me fast</gog-button>\n<p>Accepted clicks: {{ accepted() }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonDebounceExample {\n  protected readonly accepted = signal(0);\n\n  protected count(): void {\n    this.accepted.update((n) => n + 1);\n  }\n}",
    css: '',
  },
  buttonDisabled: {
    html: '@for (variant of variants; track variant) {\n  <gog-button [variant]="variant" disabled>{{ variant }}</gog-button>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent, GogVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonDisabledExample {\n  protected readonly variants: readonly GogVariant[] = ['primary', 'secondary', 'outline', 'ghost'];\n}",
    css: '',
  },
  buttonFullWidth: {
    html: '<gog-button variant="outline" fullWidth>Full width</gog-button>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonFullWidthExample {}",
    css: '',
  },
  buttonIcons: {
    html: '<!-- No visible label, so ariaLabel names the inner <button>. -->\n<gog-button variant="primary" ariaLabel="Confirm">\n  <gog-icon name="check" />\n</gog-button>\n<gog-button variant="outline" ariaLabel="Dismiss">\n  <gog-icon name="close" />\n</gog-button>\n<gog-button variant="ghost" size="sm" ariaLabel="More info">\n  <gog-icon name="info" />\n</gog-button>\n\n<!-- One height with or without an icon; no margin or &nbsp; beside it. -->\n<gog-button variant="outline">\n  <gog-icon name="download" />\n  Export\n</gog-button>\n<gog-button variant="outline">Save</gog-button>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent, IconComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, IconComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonIconsExample {}",
    css: '',
  },
  buttonLink: {
    html: '<a gogButton routerLink="/general/theming">See theming</a>\n<a\n  gogButton\n  variant="ghost"\n  href="https://www.npmjs.com/package/@guildofgleks/ui"\n  target="_blank"\n  rel="noreferrer"\n>\n  Package on npm\n</a>\n<button gogButton variant="outline" size="sm" type="button">A real button</button>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { GogButtonDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [GogButtonDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonLinkExample {}",
    css: '',
  },
  buttonLoading: {
    html: '<div>\n  <gog-button variant="primary" [loading]="saving()" (gogClick)="save()">Save</gog-button>\n</div>\n\n<!-- The spinner scales with the button. -->\n<div>\n  @for (size of sizes; track size) {\n    <gog-button\n      variant="secondary"\n      [size]="size"\n      [loading]="loading() === size"\n      (gogClick)="load(size)"\n    >\n      {{ size }}\n    </gog-button>\n  }\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent, GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonLoadingExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n  protected readonly saving = signal(false);\n  protected readonly loading = signal<GogSize | null>(null);\n\n  protected save(): void {\n    this.saving.set(true);\n    setTimeout(() => this.saving.set(false), 1500);\n  }\n\n  protected load(size: GogSize): void {\n    this.loading.set(size);\n    setTimeout(() => this.loading.set(null), 1500);\n  }\n}",
    css: '',
  },
  buttonNativeType: {
    html: '<form (submit)="onSubmit($event)" (reset)="onReset()">\n  <gog-button variant="primary" type="submit">Submit</gog-button>\n  <gog-button variant="outline" type="reset">Reset</gog-button>\n</form>\n<p>{{ result() }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonNativeTypeExample {\n  protected readonly result = signal('Neither button pressed yet.');\n\n  protected onSubmit(event: Event): void {\n    event.preventDefault();\n    this.result.set('Submitted via type=\"submit\".');\n  }\n\n  protected onReset(): void {\n    this.result.set('Reset via type=\"reset\".');\n  }\n}",
    css: '',
  },
  buttonOverview: {
    html: '<gog-button variant="primary" (gogClick)="onClick()">Click me</gog-button>\n<p>Clicked {{ clicks() }} time(s).</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonOverviewExample {\n  protected readonly clicks = signal(0);\n\n  protected onClick(): void {\n    this.clicks.update((count) => count + 1);\n  }\n}",
    css: '',
  },
  buttonPress: {
    html: '@for (variant of variants; track variant) {\n  <gog-button [variant]="variant">{{ variant }}</gog-button>\n}\n\n<!-- One instance with its own press colour: the instance tier, set inline. -->\n<gog-button\n  variant="primary"\n  style="--gog-button-press-bg: var(--gog-danger-color); --gog-button-press-color: #fff"\n>\n  custom press\n</gog-button>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent, GogVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonPressExample {\n  protected readonly variants: readonly GogVariant[] = ['primary', 'secondary', 'outline', 'ghost'];\n}",
    css: '',
  },
  buttonSeverity: {
    html: '@for (severity of severities; track severity) {\n  <div>\n    <span>{{ severity }}</span>\n    @for (variant of variants; track variant) {\n      <gog-button [variant]="variant" [severity]="severity">{{ variant }}</gog-button>\n    }\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent, GogSeverity, GogVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonSeverityExample {\n  protected readonly variants: readonly GogVariant[] = ['primary', 'secondary', 'outline', 'ghost'];\n  protected readonly severities: readonly GogSeverity[] = ['success', 'danger', 'warning', 'info'];\n}",
    css: '',
  },
  buttonVariants: {
    html: '@for (variant of variants; track variant) {\n  <div>\n    <span>{{ variant }}</span>\n    @for (size of sizes; track size) {\n      <gog-button [variant]="variant" [size]="size">{{ size }}</gog-button>\n    }\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ButtonComponent, GogSize, GogVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ButtonVariantsExample {\n  protected readonly variants: readonly GogVariant[] = ['primary', 'secondary', 'outline', 'ghost'];\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
    css: '',
  },
} as const satisfies Record<string, ExampleSource>;
