// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const STEPPER_EXAMPLES = {
  stepperFlow: {
    html: '<gog-stepper [steps]="steps()" [linear]="linear()" [(activeIndex)]="active" />\n<div>\n  <gog-button variant="secondary" [disabled]="active() === 0" (gogClick)="active.set(active() - 1)">\n    Back\n  </gog-button>\n  <gog-button (gogClick)="complete()">Mark "{{ steps()[active()].label }}" complete</gog-button>\n  <gog-button variant="ghost" (gogClick)="reset()">Start over</gog-button>\n  <gog-toggle label="linear" [(checked)]="linear" />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { StepperComponent, type GogStep, ButtonComponent, ToggleComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, StepperComponent, ToggleComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperFlowExample {\n  private readonly initial: readonly GogStep[] = [\n    { label: 'Account' },\n    { label: 'Address' },\n    { label: 'Payment' },\n    { label: 'Review' },\n  ];\n  protected readonly steps = signal<readonly GogStep[]>(this.initial);\n  protected readonly active = signal(0);\n  protected readonly linear = signal(true);\n\n  /** The app owns the data: marking a step complete is what opens the way forward. */\n  protected complete(): void {\n    const index = this.active();\n    this.steps.update((steps) =>\n      steps.map((step, i) => (i === index ? { ...step, state: 'complete' as const } : step)),\n    );\n    this.active.set(Math.min(index + 1, this.steps().length - 1));\n  }\n\n  protected reset(): void {\n    this.steps.set(this.initial);\n    this.active.set(0);\n  }\n}",
  },
  stepperNarrow: {
    html: '<div style="max-width: 14rem">\n  <gog-stepper orientation="vertical" [steps]="steps" [activeIndex]="1" />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { StepperComponent, type GogStep } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperNarrowExample {\n  /** Six steps do not fit 14rem side by side; stacked, they fit any width. */\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', state: 'complete' },\n    { label: 'Address' },\n    { label: 'Shipping' },\n    { label: 'Payment' },\n    { label: 'Confirmation' },\n    { label: 'Review' },\n  ];\n}",
  },
  stepperOverview: {
    html: '<gog-stepper [steps]="steps" [(activeIndex)]="active" />',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { StepperComponent, type GogStep } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperOverviewExample {\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', state: 'complete' },\n    { label: 'Address', state: 'complete' },\n    { label: 'Payment' },\n    { label: 'Review' },\n  ];\n  protected readonly active = signal(2);\n}",
  },
  stepperRtl: {
    html: '<div dir="rtl">\n  <gog-stepper [steps]="steps" [activeIndex]="1" />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { StepperComponent, type GogStep } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperRtlExample {\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', state: 'complete' },\n    { label: 'Address' },\n    { label: 'Review' },\n  ];\n}",
  },
  stepperSizes: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>{{ size }}</span>\n    <gog-stepper [size]="size" [steps]="steps" [activeIndex]="1" />\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { StepperComponent, type GogStep, type GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', state: 'complete' },\n    { label: 'Address' },\n    { label: 'Review' },\n  ];\n}",
  },
  stepperStates: {
    html: '<gog-stepper [steps]="steps" [activeIndex]="2" [linear]="false" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { StepperComponent, type GogStep } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperStatesExample {\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', description: 'Done', state: 'complete' },\n    { label: 'Card', description: 'Declined', state: 'error' },\n    { label: 'Address', description: 'Current' },\n    { label: 'Newsletter', optional: true },\n    { label: 'Gift wrap', disabled: true },\n    { label: 'Review' },\n  ];\n}",
  },
  stepperVertical: {
    html: '<gog-stepper orientation="vertical" [steps]="steps" [activeIndex]="2" [linear]="false" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { StepperComponent, type GogStep } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [StepperComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class StepperVerticalExample {\n  protected readonly steps: readonly GogStep[] = [\n    { label: 'Account', description: 'Done', state: 'complete' },\n    { label: 'Card', description: 'Declined', state: 'error' },\n    { label: 'Address', description: 'Current' },\n    { label: 'Newsletter', optional: true },\n    { label: 'Gift wrap', disabled: true },\n    { label: 'Review' },\n  ];\n}",
  },
} as const satisfies Record<string, ExampleSource>;
