// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const RATING_EXAMPLES = {
  ratingClearable: {
    html: '<div>\n  <gog-rating label="Out of ten" [max]="10" size="sm" [(value)]="outOfTen" />\n  <p>value: {{ outOfTen() }}</p>\n</div>\n<div>\n  <gog-rating label="Press the chosen star again" clearable [(value)]="clearable" />\n  <p>value: {{ clearable() }}</p>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { RatingComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [RatingComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingClearableExample {\n  protected readonly outOfTen = signal<number | null>(7);\n  protected readonly clearable = signal<number | null>(4);\n}",
  },
  ratingForms: {
    html: '<div>\n  <gog-rating\n    label="Rate the delivery"\n    errorMessage="Pick a rating"\n    errorDisplay="auto"\n    [formControl]="delivery"\n  />\n  <p>value {{ delivery.value }} · touched {{ delivery.touched }} · valid {{ delivery.valid }}</p>\n</div>\n<div>\n  <gog-button variant="secondary" size="sm" (gogClick)="delivery.markAsTouched()">\n    markAsTouched()\n  </gog-button>\n  <gog-button variant="ghost" size="sm" (gogClick)="delivery.reset()">reset()</gog-button>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';\nimport { RatingComponent, ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, RatingComponent, ReactiveFormsModule],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingFormsExample {\n  protected readonly delivery = new FormControl<number | null>(null, Validators.required);\n}",
  },
  ratingOverview: {
    html: '<div>\n  <gog-rating label="Your rating" [(value)]="score" />\n  <p>value: {{ score() }}</p>\n</div>\n<div>\n  <gog-rating label="Average" readonly [value]="4.7" />\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { RatingComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [RatingComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingOverviewExample {\n  protected readonly score = signal<number | null>(3);\n}",
  },
  ratingReadonly: {
    html: '@for (value of values; track $index) {\n  <div>\n    <span>{{ value ?? \'null\' }}</span>\n    <gog-rating readonly size="sm" [value]="value" />\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RatingComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [RatingComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingReadonlyExample {\n  protected readonly values: readonly (number | null)[] = [0, 1.2, 2.5, 3.7, 4.3, 5, null];\n}",
  },
  ratingSizes: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>{{ size }}</span>\n    <gog-rating ariaLabel="Score" [size]="size" [value]="3" />\n    <gog-rating readonly [size]="size" [value]="3.5" />\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RatingComponent, type GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [RatingComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
  },
  ratingStates: {
    html: '<gog-rating label="Your stay" [value]="3" />\n<gog-rating label="Your stay" [value]="3" errorMessage="Rate your stay" />\n<gog-rating label="Your stay" [value]="3" disabled />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RatingComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [RatingComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class RatingStatesExample {}",
  },
} as const satisfies Record<string, ExampleSource>;
