// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const TEXTAREA_EXAMPLES = {
  textareaClearable: {
    html: '<gog-textarea label="One line" value="Ship on Friday." [rows]="4" clearable />\n<!-- The button steps clear of the scrollbar once the content overflows. -->\n<gog-textarea label="Overflowing" [value]="longText" [rows]="4" clearable />\n<gog-textarea\n  label="clearAriaLabel"\n  value="Ship on Friday."\n  [rows]="4"\n  clearable\n  clearAriaLabel="Erase notes"\n/>\n<!-- Nothing to clear when nothing can be edited. -->\n<gog-textarea label="Readonly: no button" value="Ship on Friday." [rows]="4" clearable readonly />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaClearableExample {\n  protected readonly longText = [\n    'A first line long enough to run the whole width of the field and reach its end edge.',\n    'Second line.',\n    'Third line.',\n    'Fourth line.',\n    'Fifth line.',\n    'Sixth line.',\n  ].join('\\n');\n}",
    css: '',
  },
  textareaConfig: {
    html: '<gog-textarea label="Size from the config (lg)" placeholder="Placeholder" [rows]="2" />\n<gog-textarea\n  label=\'size="sm" — the instance wins\'\n  size="sm"\n  placeholder="Placeholder"\n  [rows]="2"\n/>\n<!-- clearable, no grip and the float label all come from the config. -->\n<gog-textarea label="Notes" value="Ship on Friday." [rows]="2" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent, provideGogConfig } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  // Usually in app.config.ts; here on the component, so it reaches only its own fields.\n  providers: [\n    provideGogConfig({\n      control: { size: 'lg', clearable: true },\n      floatLabel: { variant: 'over' },\n      textarea: { resize: 'none' },\n    }),\n  ],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaConfigExample {}",
    css: '',
  },
  textareaFloatLabel: {
    html: '@for (variant of variants; track variant) {\n  <gog-textarea\n    [floatLabel]="variant"\n    [label]="\'floatLabel: \' + variant"\n    placeholder="Anything to add?"\n    [rows]="2"\n  />\n  <gog-textarea\n    [floatLabel]="variant"\n    [label]="\'floatLabel: \' + variant"\n    value="Ship on Friday."\n    [rows]="2"\n  />\n}\n\n<!-- The placeholder shows under the floated label once it has somewhere to float to. -->\n<gog-textarea\n  floatLabel="over"\n  floatLabelShowPlaceholder\n  label="floatLabelShowPlaceholder"\n  placeholder="Anything to add?"\n  [rows]="2"\n/>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent, type GogFloatLabelVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaFloatLabelExample {\n  protected readonly variants: readonly GogFloatLabelVariant[] = ['none', 'in', 'on', 'over'];\n}",
    css: '',
  },
  textareaForms: {
    html: '<div>\n  <gog-textarea\n    label="Feedback (reactive form)"\n    placeholder="What should we change?"\n    [rows]="2"\n    [formControl]="control"\n    errorMessage="At least 10 characters"\n    errorDisplay="auto"\n  />\n  <div>\n    <gog-button variant="outline" size="sm" (gogClick)="control.markAsTouched()">\n      markAsTouched()\n    </gog-button>\n    <gog-button variant="outline" size="sm" (gogClick)="toggleDisabled()">\n      {{ control.disabled ? \'enable()\' : \'disable()\' }}\n    </gog-button>\n  </div>\n  <code>\n    {{ control.value.length }} characters · valid: {{ control.valid }} · touched:\n    {{ control.touched }} · disabled: {{ control.disabled }}\n  </code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';\nimport { ButtonComponent, TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, ReactiveFormsModule, TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaFormsExample {\n  protected readonly control = new FormControl('', {\n    nonNullable: true,\n    validators: [Validators.required, Validators.minLength(10)],\n  });\n\n  protected toggleDisabled(): void {\n    if (this.control.disabled) {\n      this.control.enable();\n    } else {\n      this.control.disable();\n    }\n  }\n}",
    css: '',
  },
  textareaManualError: {
    html: '<!-- errorDisplay="manual" (the default): shown for as long as errorMessage is non-empty. -->\n<gog-textarea\n  label="Feedback"\n  placeholder="At least 10 characters"\n  [rows]="3"\n  [(value)]="feedback"\n  [errorMessage]="feedback().length > 0 && feedback().length < 10 ? \'At least 10 characters\' : \'\'"\n/>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaManualErrorExample {\n  protected readonly feedback = signal('');\n}",
    css: '',
  },
  textareaNative: {
    html: '<div>\n  <gog-textarea\n    label="Commit message"\n    name="message"\n    placeholder="Up to 72 characters"\n    [rows]="2"\n    [maxlength]="72"\n    [spellcheck]="true"\n  />\n</div>\n<div>\n  <!-- spellcheck off: a code snippet is not prose. -->\n  <gog-textarea label="Snippet" [rows]="2" [spellcheck]="false" [minlength]="3" [(value)]="code" />\n  <code>{{ code().length }} characters</code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaNativeExample {\n  protected readonly code = signal('');\n}",
    css: '',
  },
  textareaOverview: {
    html: '<div>\n  <gog-textarea\n    label="Bio"\n    placeholder="Tell us about yourself"\n    [rows]="3"\n    [(value)]="bio"\n    (valueChange)="changes.update((n) => n + 1)"\n  />\n  <code>{{ bio().length }} characters · {{ changes() }} valueChange</code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaOverviewExample {\n  protected readonly bio = signal('');\n  protected readonly changes = signal(0);\n}",
    css: '',
  },
  textareaResize: {
    html: '<!-- The grip is the library\'s own; the drag underneath it is the browser\'s. -->\n<gog-textarea label="resize unset (vertical)" value="Ship on Friday." [rows]="2" />\n<gog-textarea label=\'resize="horizontal"\' value="Ship on Friday." [rows]="2" resize="horizontal" />\n<gog-textarea label=\'resize="both"\' value="Ship on Friday." [rows]="2" resize="both" />\n<gog-textarea label=\'resize="none"\' value="Ship on Friday." [rows]="2" resize="none" />\n<gog-textarea label="Disabled: no grip" value="Ship on Friday." [rows]="2" disabled />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaResizeExample {}",
    css: '',
  },
  textareaRows: {
    html: '<gog-textarea label=\'[rows]="2"\' placeholder="Placeholder" [rows]="2" />\n<gog-textarea label="rows unset (4)" placeholder="Placeholder" />\n<gog-textarea label=\'[rows]="8"\' placeholder="Placeholder" [rows]="8" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaRowsExample {}",
    css: '',
  },
  textareaSizes: {
    html: '@for (size of sizes; track size) {\n  <gog-textarea [size]="size" [label]="\'size: \' + size" placeholder="Placeholder" [rows]="2" />\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent, type GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
    css: '',
  },
  textareaStates: {
    html: '<gog-textarea label="Default" placeholder="Placeholder" [rows]="2" />\n<gog-textarea label="Disabled" value="Ship on Friday." [rows]="2" disabled />\n<!-- Focusable, selectable and submitted with the form; only edits are blocked. -->\n<gog-textarea label="Readonly" value="Ship on Friday." [rows]="2" readonly />\n<gog-textarea label="Error" placeholder="Placeholder" [rows]="2" errorMessage="Required field" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaStatesExample {}",
    css: '',
  },
  textareaWidth: {
    html: '<gog-textarea label="fullWidth (default)" placeholder="Fills the container" [rows]="2" />\n<gog-textarea\n  label=\'[fullWidth]="false"\'\n  [fullWidth]="false"\n  placeholder="Shrinks to content"\n  [rows]="2"\n/>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { TextareaComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [TextareaComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class TextareaWidthExample {}",
    css: '',
  },
} as const satisfies Record<string, ExampleSource>;
