// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const DIVIDER_EXAMPLES = {
  dividerInset: {
    html: '@for (step of steps; track step.label; let last = $last) {\n  <span><gog-icon [name]="step.icon" /> {{ step.label }}</span>\n  @if (!last) {\n    <!-- Starts under the text, not under the icon. -->\n    <gog-divider inset />\n  }\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent, GogIconName, IconComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent, IconComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerInsetExample {\n  protected readonly steps: { icon: GogIconName; label: string }[] = [\n    { icon: 'success', label: 'Order placed' },\n    { icon: 'clock', label: 'Awaiting payment' },\n    { icon: 'info', label: 'Preparing shipment' },\n  ];\n}",
  },
  dividerLabels: {
    html: '<gog-divider>OR</gog-divider>\n<gog-divider>\n  <gog-icon name="info" />\n  Shipping details\n</gog-divider>\n<gog-divider><gog-tag variant="info" size="xsm">New</gog-tag></gog-divider>\n<gog-divider><gog-icon name="star" /></gog-divider>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent, IconComponent, TagComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent, IconComponent, TagComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerLabelsExample {}",
  },
  dividerOverview: {
    html: '<p>Above the rule.</p>\n<gog-divider />\n<p>Below it.</p>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerOverviewExample {}",
  },
  dividerTokens: {
    html: '<gog-divider />\n<!-- Instance tokens: one divider heavier and coloured, without touching the theme. -->\n<gog-divider style="--gog-divider-color: var(--gog-accent-color); --gog-divider-thickness: 3px">\n  Accent, 3px\n</gog-divider>\n<gog-divider style="--gog-divider-spacing: 32px">More room around it</gog-divider>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerTokensExample {}",
  },
  dividerVariants: {
    html: '<!-- With nothing projected the label collapses and the two halves meet as one line. -->\n@for (variant of variants; track variant) {\n  <p>variant="{{ variant }}"</p>\n  <gog-divider [variant]="variant" />\n  <gog-divider [variant]="variant">OR</gog-divider>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent, GogDividerVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerVariantsExample {\n  protected readonly variants: GogDividerVariant[] = ['solid', 'dashed', 'dotted'];\n}",
  },
  dividerVertical: {
    html: '<div>\n  <span>Bold</span>\n  <span>Italic</span>\n  <gog-divider orientation="vertical" />\n  <span>Link</span>\n  <gog-divider orientation="vertical" variant="dashed" />\n  <span>Undo</span>\n  <span>Redo</span>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { DividerComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [DividerComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class DividerVerticalExample {}",
  },
} as const satisfies Record<string, ExampleSource>;
