// GENERATED by scripts/generate-deprecations.mjs — do not edit by hand.
// Run `npm run generate:deprecations`; `npm run check:deprecations` fails on a stale copy.

/** What kind of thing a deprecation is about: an exported symbol, or a CSS custom property. */
export type GogDeprecationKind = 'symbol' | 'token';

/** One deprecated part of the public API, with the version that removes it. */
export interface GogDeprecation {
  kind: GogDeprecationKind;
  /** The deprecated name — an export, an input, or a `--gog-*` custom property. */
  name: string;
  /** What to use instead. */
  replacement: string;
  /** The version that deprecated it, and the day it was announced. */
  since: string;
  sinceDate: string;
  /** The version that removes it. Until then, the deprecated name still works. */
  removedIn: string;
}

/**
 * Everything `@guildofgleks/ui` currently deprecates: 28 symbol(s) and 3 token(s).
 *
 * Generated from the library's own source — `@deprecated` tags for symbols, and the stylesheets
 * themselves for tokens — so it cannot drift from what actually still resolves. Meant for tooling
 * that has to answer "is this still supported, and until when?": a docs site marking an API row,
 * an editor plugin, a codemod.
 *
 * An empty `symbol` half means exactly what it says: nothing in the TypeScript API is deprecated
 * right now.
 */
export const GOG_DEPRECATIONS: readonly GogDeprecation[] = [
  {
    kind: 'symbol',
    name: 'CalendarComponent',
    replacement:
      'import it from `@guildofgleks/ui/datepicker`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'ConfirmationDialogComponent',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'ConfirmDialogData',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DatepickerComponent',
    replacement:
      'import it from `@guildofgleks/ui/datepicker`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'defaultCompare',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DIALOG_DATA',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DIALOG_REF',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DialogComponent',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DialogConfig',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DialogHandle',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DialogRef',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'DialogService',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'getByPath',
    replacement:
      "read the field yourself; this is the package's own plumbing and it leaves the root. It stays inside `@guildofgleks/ui/shared`, the internal entry point, which is not a replacement to build on.",
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogCalendarDay',
    replacement:
      'import it from `@guildofgleks/ui/datepicker`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogColumn',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogColumnBodyContext',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogColumnBodyDirective',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogColumnHeaderContext',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogColumnHeaderDirective',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogDatepickerValue',
    replacement:
      'import it from `@guildofgleks/ui/datepicker`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogTableRowClickEvent',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogTableSelectionMode',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'GogTableSortEvent',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'isSameOptionValue',
    replacement:
      "read the field yourself; this is the package's own plumbing and it leaves the root. It stays inside `@guildofgleks/ui/shared`, the internal entry point, which is not a replacement to build on.",
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'OpenDialog',
    replacement:
      'import it from `@guildofgleks/ui/dialog`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'readOption',
    replacement:
      "read the field yourself; this is the package's own plumbing and it leaves the root. It stays inside `@guildofgleks/ui/shared`, the internal entry point, which is not a replacement to build on.",
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'SortDirection',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'symbol',
    name: 'TableComponent',
    replacement:
      'import it from `@guildofgleks/ui/table`. From that minor on it stays out of the initial bundle of an app that only uses it behind a lazy route.',
    since: '21.13.0',
    sinceDate: '2026-09-13',
    removedIn: '21.14.0',
  },
  {
    kind: 'token',
    name: '--gog-multiselect-panel-offset',
    replacement: '--gog-multiselect-panel-gap',
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
  {
    kind: 'token',
    name: '--gog-select-panel-offset',
    replacement: '--gog-select-panel-gap',
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
  {
    kind: 'token',
    name: '--gog-slider-thumb-shadow',
    replacement: '--gog-slider-thumb-glow-color',
    since: '21.13.0',
    sinceDate: '2026-09-12',
    removedIn: '21.14.0',
  },
];
