// GENERATED by scripts/generate-deprecations.mjs — do not edit by hand.
// Run `npm run generate:deprecations`; `npm run check:deprecations` fails on a stale copy.

/** What kind of thing a deprecation is about: an exported symbol, or a CSS custom property. */
export type GogDeprecationKind = 'symbol' | 'token';

/** One deprecated part of the public API, with the version that removes it. */
export interface GogDeprecation {
  kind: GogDeprecationKind;
  /** The deprecated name — an export, an input, or a `--gog-*` custom property. */
  name: string;
  /** What to use instead. */
  replacement: string;
  /** The version that deprecated it, and the day it was announced. */
  since: string;
  sinceDate: string;
  /** The version that removes it. Until then, the deprecated name still works. */
  removedIn: string;
}

/**
 * Everything `@guildofgleks/ui` currently deprecates: 0 symbol(s) and 0 token(s).
 *
 * Generated from the library's own source — `@deprecated` tags for symbols, and the stylesheets
 * themselves for tokens — so it cannot drift from what actually still resolves. Meant for tooling
 * that has to answer "is this still supported, and until when?": a docs site marking an API row,
 * an editor plugin, a codemod.
 *
 * An empty `symbol` half means exactly what it says: nothing in the TypeScript API is deprecated
 * right now.
 */
export const GOG_DEPRECATIONS: readonly GogDeprecation[] = [];
