// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const FILE_UPLOAD_EXAMPLES = {
  fileUploadForms: {
    html: '<div>\n  <gog-file-upload\n    label="Signed contract"\n    accept=".pdf"\n    errorMessage="Attach the signed contract"\n    errorDisplay="auto"\n    [formControl]="contract"\n  />\n  <p>\n    {{ contract.value.length }} file(s) · touched {{ contract.touched }} · valid\n    {{ contract.valid }}\n  </p>\n</div>\n<div>\n  <gog-button variant="secondary" size="sm" (gogClick)="contract.markAsTouched()">\n    markAsTouched()\n  </gog-button>\n  <gog-button variant="ghost" size="sm" (gogClick)="contract.reset()">reset()</gog-button>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';\nimport { FileUploadComponent, ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, FileUploadComponent, ReactiveFormsModule],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadFormsExample {\n  protected readonly contract = new FormControl<File[]>([], {\n    nonNullable: true,\n    validators: Validators.required,\n  });\n}",
  },
  fileUploadOverview: {
    html: '<gog-file-upload\n  label="Contract"\n  hint="PDF, up to 5 MB"\n  accept=".pdf"\n  [maxSize]="5 * 1024 * 1024"\n/>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FileUploadComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [FileUploadComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadOverviewExample {}",
  },
  fileUploadSingle: {
    html: '<gog-file-upload label="Avatar" hint="One image; a new one replaces it" accept="image/*" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FileUploadComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [FileUploadComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadSingleExample {}",
  },
  fileUploadSizes: {
    html: '@for (size of sizes; track size) {\n  <gog-file-upload label="Attachment" [hint]="size" [size]="size" />\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FileUploadComponent, type GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [FileUploadComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
  },
  fileUploadStates: {
    html: '<gog-file-upload label="Contract" hint="PDF" accept=".pdf" />\n<gog-file-upload\n  label="Contract"\n  hint="PDF"\n  accept=".pdf"\n  errorMessage="Attach the signed contract"\n/>\n<gog-file-upload label="Contract" hint="PDF" accept=".pdf" disabled />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FileUploadComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [FileUploadComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadStatesExample {}",
  },
  fileUploadValidation: {
    html: '<gog-file-upload\n  label="Documents"\n  hint="PDF or images, up to 1 MB each, at most three"\n  accept=".pdf,image/*"\n  multiple\n  [maxSize]="1024 * 1024"\n  [maxFiles]="3"\n  [(value)]="files"\n  (gogReject)="rejected.set($event)"\n/>\n<p>{{ files().length }} file(s) chosen</p>\n@for (refusal of rejected(); track refusal.file) {\n  <p>{{ refusal.file.name }} — refused: {{ refusal.reason }}</p>\n}',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { FileUploadComponent, type GogFileRejection } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [FileUploadComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class FileUploadValidationExample {\n  protected readonly files = signal<File[]>([]);\n  protected readonly rejected = signal<GogFileRejection[]>([]);\n}",
  },
} as const satisfies Record<string, ExampleSource>;
