// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const INPUTFIELD_EXAMPLES = {
  inputfieldAddons: {
    html: '<gog-inputfield label="Amount" [(value)]="amount">\n  <span gogInputAddonStart>$</span>\n  <span gogInputAddonEnd>USD</span>\n</gog-inputfield>\n\n<!-- The field makes room for an addon wider than an icon. -->\n<gog-inputfield label="Website" [(value)]="website">\n  <span gogInputAddonStart>https://</span>\n</gog-inputfield>\n\n<!-- An actionable addon is a real button with its own name and click. -->\n<div>\n  <gog-inputfield label="Search" [(value)]="search">\n    <button type="button" gogInputAddonEnd aria-label="Run search" (click)="run()">\n      <gog-icon name="search" />\n    </button>\n  </gog-inputfield>\n  <code>{{ lastSearch() }}</code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport {\n  InputfieldComponent,\n  GogInputAddonEndDirective,\n  GogInputAddonStartDirective,\n  IconComponent,\n} from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [\n    InputfieldComponent,\n    GogInputAddonEndDirective,\n    GogInputAddonStartDirective,\n    IconComponent,\n  ],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldAddonsExample {\n  protected readonly amount = signal('');\n  protected readonly website = signal('');\n  protected readonly search = signal('');\n  protected readonly lastSearch = signal('No search yet.');\n\n  protected run(): void {\n    this.lastSearch.set(`Searched for \"${this.search()}\"`);\n  }\n}",
    css: '',
  },
  inputfieldClearable: {
    html: '<!-- Appears once there is something to clear, and goes when there is not. -->\n<gog-inputfield label="Name" clearable [(value)]="name" />\n<gog-inputfield label="Empty" placeholder="Type to see it" clearable />',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldClearableExample {\n  protected readonly name = signal('Ada Lovelace');\n}",
    css: '',
  },
  inputfieldConfig: {
    html: '<gog-inputfield label="Size and float label from the config" placeholder="Placeholder" />\n<gog-inputfield label=\'size="sm" — the instance wins\' size="sm" placeholder="Placeholder" />\n<!-- control.clearable: every field gets a clear button without asking. -->\n<gog-inputfield label="Clearable from the config" value="42" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, provideGogConfig } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  // Usually in app.config.ts; here on the component, so it reaches only its own fields.\n  providers: [\n    provideGogConfig({\n      control: { size: 'lg', clearable: true },\n      floatLabel: { variant: 'over' },\n    }),\n  ],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldConfigExample {}",
    css: '',
  },
  inputfieldError: {
    html: '<!-- errorDisplay="manual" (the default): the message shows while it is non-empty. -->\n<gog-inputfield\n  label="Username"\n  [(value)]="username"\n  [errorMessage]="username().length > 0 && username().length < 3 ? \'At least 3 characters\' : \'\'"\n/>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldErrorExample {\n  protected readonly username = signal('');\n}",
    css: '',
  },
  inputfieldFloatLabel: {
    html: '@for (variant of variants; track variant) {\n  <gog-inputfield\n    [floatLabel]="variant"\n    [label]="\'floatLabel: \' + variant"\n    placeholder="e.g. Ada"\n  />\n  <gog-inputfield [floatLabel]="variant" [label]="\'floatLabel: \' + variant" value="Ada Lovelace" />\n}\n\n<!-- The placeholder shows under the floated label once it has somewhere to float to. -->\n<gog-inputfield\n  floatLabel="over"\n  floatLabelShowPlaceholder\n  label="floatLabelShowPlaceholder"\n  placeholder="e.g. Ada"\n/>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, GogFloatLabelVariant } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldFloatLabelExample {\n  protected readonly variants: readonly GogFloatLabelVariant[] = ['none', 'in', 'on', 'over'];\n}",
    css: '',
  },
  inputfieldForms: {
    html: '<div>\n  <gog-inputfield\n    label="Email (reactive form)"\n    placeholder="jane@example.com"\n    [formControl]="control"\n    errorMessage="Enter a valid email"\n    errorDisplay="auto"\n  />\n  <div>\n    <gog-button variant="outline" size="sm" (gogClick)="control.markAsTouched()">\n      markAsTouched()\n    </gog-button>\n    <gog-button variant="outline" size="sm" (gogClick)="toggleDisabled()">\n      {{ control.disabled ? \'enable()\' : \'disable()\' }}\n    </gog-button>\n  </div>\n  <code>\n    value: "{{ control.value }}" · touched: {{ control.touched }} · disabled: {{ control.disabled }}\n  </code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';\nimport { InputfieldComponent, ButtonComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent, ButtonComponent, ReactiveFormsModule],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldFormsExample {\n  protected readonly control = new FormControl('', [Validators.required, Validators.email]);\n\n  protected toggleDisabled(): void {\n    if (this.control.disabled) {\n      this.control.enable();\n    } else {\n      this.control.disable();\n    }\n  }\n}",
    css: '',
  },
  inputfieldIcons: {
    html: '<!-- A bare icon name: decorative, an aria-hidden span, never a button. -->\n<gog-inputfield label="Search" iconStart="search" placeholder="Search…" />\n<gog-inputfield label="Favourite" iconEnd="star" placeholder="Item" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldIconsExample {}",
    css: '',
  },
  inputfieldNumberDate: {
    html: '<!-- Through a formControl a number field\'s value is a number (null when empty). -->\n<div>\n  <gog-inputfield label="Quantity" type="number" [min]="1" [max]="10" [formControl]="quantity" />\n  <code>{{ quantity.value }} ({{ typeOf(quantity.value) }})</code>\n</div>\n<!-- [(value)] always hands back the string. -->\n<div>\n  <gog-inputfield label="Delivery date" type="date" [(value)]="delivery" />\n  <code>"{{ delivery() }}" ({{ typeOf(delivery()) }})</code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { FormControl, ReactiveFormsModule } from '@angular/forms';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent, ReactiveFormsModule],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldNumberDateExample {\n  protected readonly quantity = new FormControl<number | null>(3);\n  protected readonly delivery = signal('');\n\n  protected typeOf(value: unknown): string {\n    return value === null ? 'null' : typeof value;\n  }\n}",
    css: '',
  },
  inputfieldNumberEnd: {
    html: '<gog-inputfield type="number" label="iconEnd" iconEnd="star" value="5" />\n<gog-inputfield type="number" label="Unit" value="5">\n  <span gogInputAddonEnd>kg</span>\n</gog-inputfield>\n<!-- While there is a value, the clear button takes the place beside the stepper. -->\n<gog-inputfield type="number" label="Clear wins" clearable iconEnd="star" value="5" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, GogInputAddonEndDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent, GogInputAddonEndDirective],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldNumberEndExample {}",
    css: '',
  },
  inputfieldOverview: {
    html: '<div>\n  <gog-inputfield\n    label="Name"\n    placeholder="Ada Lovelace"\n    [(value)]="name"\n    (valueChange)="changes.update((n) => n + 1)"\n  />\n  <code>value: "{{ name() }}" · {{ changes() }} valueChange</code>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldOverviewExample {\n  protected readonly name = signal('');\n  protected readonly changes = signal(0);\n}",
    css: '',
  },
  inputfieldPassword: {
    html: '<gog-inputfield type="password" label="Password" value="secret" />\n<!-- The reveal toggle keeps the outer edge; iconEnd or an addon sits beside it. -->\n<gog-inputfield type="password" label="With iconEnd" iconEnd="lock" value="secret" />\n<gog-inputfield type="password" label="With an addon" value="secret">\n  <span gogInputAddonEnd>PIN</span>\n</gog-inputfield>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, GogInputAddonEndDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent, GogInputAddonEndDirective],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldPasswordExample {}",
    css: '',
  },
  inputfieldSizes: {
    html: '@for (size of sizes; track size) {\n  <gog-inputfield [size]="size" [label]="size" placeholder="Placeholder" />\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
    css: '',
  },
  inputfieldStates: {
    html: '<gog-inputfield label="Default" placeholder="Placeholder" />\n<gog-inputfield label="Disabled" value="Value" disabled />\n<!-- readonly: focusable and selectable, but not editable. -->\n<gog-inputfield label="Readonly" value="Value" readonly />\n<gog-inputfield label="Error" errorMessage="Required field" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldStatesExample {}",
    css: '',
  },
  inputfieldStepper: {
    html: '<gog-inputfield type="number" label="Stepper" value="5" />\n<!-- The arrow keys and the wheel still step: that is native number-input behaviour. -->\n<gog-inputfield type="number" label="No stepper" [showSpinButtons]="false" value="5" />\n<!-- At a bound the button for that direction is disabled. -->\n<gog-inputfield\n  type="number"\n  label="At max (0–10, step 2)"\n  [min]="0"\n  [max]="10"\n  [step]="2"\n  value="10"\n/>\n<gog-inputfield\n  type="number"\n  label="At min (0–10, step 2)"\n  [min]="0"\n  [max]="10"\n  [step]="2"\n  value="0"\n/>\n<gog-inputfield type="number" label="Clearable and stepper" clearable value="5" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldStepperExample {}",
    css: '',
  },
  inputfieldTypes: {
    html: '@for (type of types; track type.type) {\n  <gog-inputfield [type]="type.type" [label]="type.type" [placeholder]="type.placeholder" />\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent, GogInputType } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldTypesExample {\n  protected readonly types: readonly { type: GogInputType; placeholder: string }[] = [\n    { type: 'text', placeholder: 'Jane Doe' },\n    { type: 'password', placeholder: 'Enter password' },\n    { type: 'email', placeholder: 'jane@example.com' },\n    { type: 'number', placeholder: '0' },\n    { type: 'search', placeholder: 'Search…' },\n    { type: 'tel', placeholder: '+1 555 0100' },\n    { type: 'url', placeholder: 'https://example.com' },\n    { type: 'date', placeholder: '' },\n    { type: 'time', placeholder: '' },\n    { type: 'datetime-local', placeholder: '' },\n  ];\n}",
    css: '',
  },
  inputfieldWidth: {
    html: '<gog-inputfield label="fullWidth (default)" placeholder="Fills the container" />\n<gog-inputfield label=\'[fullWidth]="false"\' [fullWidth]="false" placeholder="00000" />',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { InputfieldComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [InputfieldComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class InputfieldWidthExample {}",
    css: '',
  },
} as const satisfies Record<string, ExampleSource>;
