#!/usr/bin/env node
/**
 * Generates `projects/gleks-ui-lab/public/sitemap.xml` from the site's own navigation.
 *
 * **`nav-data.ts` is the source.** The sitemap must list the pages the site actually links to,
 * and that file is already the single place those are declared — deriving from it means adding
 * a component page to the sidebar adds it to the sitemap, with no second list to forget. The
 * router's `app.routes.ts` is deliberately *not* the source: it also carries the
 * `components/:name` and `general/:slug` catch-alls, which render for any slug and must never
 * be advertised to a crawler (SeoService marks those `noindex`).
 *
 * `scripts/build-lab.mjs` runs this before every lab build, so a deployed image cannot ship a
 * stale sitemap. `--check` fails instead of writing, for use in CI.
 *
 * No `<lastmod>`: an honest value would need per-page git history, and a generated "today"
 * lies to crawlers about every page at once — which is worse than omitting the field, since
 * Google discounts the whole signal once it catches a site doing it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const navDataPath = path.join(
  rootDir,
  'projects/gleks-ui-lab/src/app/components/shared/nav-data.ts',
);
const sitemapPath = path.join(rootDir, 'projects/gleks-ui-lab/public/sitemap.xml');

const SITE_URL = 'https://ui.guildofgleks.com';

/**
 * Routed pages that exist and are worth indexing but are not in the sidebar — the theme
 * generator is linked from the Theming page instead. Keep this list short; anything permanent
 * belongs in the nav.
 */
const EXTRA_PATHS = ['general/theme-generator'];

/** `/` redirects here (app.routes.ts), so this is the canonical home page. */
const HOME_PATH = 'general/overview';

function readNavPaths() {
  const source = readFileSync(navDataPath, 'utf8');
  const paths = [...source.matchAll(/path:\s*'([^']+)'/g)].map((m) => m[1]);
  if (paths.length === 0) {
    throw new Error(`No "path: '…'" entries found in ${navDataPath} — did its shape change?`);
  }
  return paths;
}

/**
 * Priority is a hint about relative importance *within this site*, nothing more. The home page
 * leads, the pages that answer "should I adopt this" come next, component reference last —
 * that ordering is what a reader arriving from search is looking for, in that order.
 */
function priorityFor(pagePath) {
  if (pagePath === HOME_PATH) return '1.0';
  if (pagePath === 'general/getting-started' || pagePath === 'general/compare') return '0.9';
  if (pagePath.startsWith('general/')) return '0.8';
  return '0.7';
}

export function buildSitemap() {
  const paths = [...new Set([...readNavPaths(), ...EXTRA_PATHS])];
  // Sorted so the file is stable across runs; the home page is pulled to the front because a
  // sitemap is also read by humans often enough to be worth ordering.
  const ordered = [HOME_PATH, ...paths.filter((p) => p !== HOME_PATH).sort()];

  const entries = ordered
    .map(
      (p) =>
        `  <url>\n    <loc>${SITE_URL}/${p}</loc>\n` +
        `    <changefreq>weekly</changefreq>\n    <priority>${priorityFor(p)}</priority>\n  </url>`,
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.mjs from nav-data.ts — do not edit by hand.
     Run \`npm run generate:sitemap\` (or any \`npm run build:lab\`) to refresh it. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function main() {
  const sitemap = buildSitemap();
  // Line endings are normalised before comparing, for the same reason generate-tokens.mjs does
  // it: a Windows checkout has CRLF on disk while this renders LF, and a byte compare would
  // report a file that is in fact identical.
  const normalize = (s) => s.replace(/\r\n/g, '\n');

  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(sitemapPath, 'utf8');
    } catch {
      console.error('sitemap.xml is missing. Run `npm run generate:sitemap`.');
      process.exit(1);
    }
    if (normalize(current) !== normalize(sitemap)) {
      console.error('sitemap.xml is out of date. Run `npm run generate:sitemap`.');
      process.exit(1);
    }
    console.log('sitemap.xml is up to date.');
    return;
  }

  let existing = '';
  try {
    existing = readFileSync(sitemapPath, 'utf8');
  } catch {
    /* first run */
  }
  const crlf = existing.includes('\r\n');
  writeFileSync(sitemapPath, crlf ? sitemap.replace(/\r?\n/g, '\r\n') : sitemap, 'utf8');
  console.log(`Generated sitemap.xml — ${sitemap.match(/<loc>/g)?.length ?? 0} URLs.`);
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main();
}
