// GENERATED FILE — do not edit by hand.
// Run `npm run generate:examples` after adding or editing an *.example.ts file in this folder.
// See scripts/generate-example-sources.mjs for why the source text is generated rather than imported.

import { DialogCustomContentExample } from './dialog-custom-content.example';
import { DialogOptionsExample } from './dialog-options.example';
import { DialogOverviewExample } from './dialog-overview.example';
import { DialogStackedExample } from './dialog-stacked.example';

/** Source text of this folder's examples, keyed by the example component itself. */
export const DIALOG_EXAMPLE_SOURCES: ReadonlyMap<unknown, string> = new Map<unknown, string>([
  [
    DialogCustomContentExample,
    "import { Component, inject } from '@angular/core';\nimport {\n  ButtonComponent,\n  DIALOG_DATA,\n  DIALOG_REF,\n  DialogRef,\n  DialogService,\n} from '@guildofgleks/ui';\n\ninterface DemoDialogData {\n  message: string;\n}\n\n@Component({\n  selector: 'app-dialog-body',\n  imports: [ButtonComponent],\n  template: `\n    <p>{{ data.message }}</p>\n    <gog-button (gogClick)=\"ref.close('closed-from-body')\">Close</gog-button>\n  `,\n})\nexport class DialogBodyComponent {\n  protected readonly data = inject<DemoDialogData>(DIALOG_DATA);\n  protected readonly ref = inject<DialogRef<string>>(DIALOG_REF);\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  template: `\n    <gog-button (gogClick)=\"openCustomContent()\">Open custom dialog</gog-button>\n    <!-- <gog-dialog /> is mounted once at the root of the app, not here — see the import\n         snippet above. This page mounts it in its own root component, and the StackBlitz\n         project this example opens in does the same. -->\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-wrap: wrap;\n      align-items: center;\n      gap: 12px;\n    }\n  `,\n})\nexport class DialogCustomContentExample {\n  private readonly dialogService = inject(DialogService);\n\n  protected openCustomContent(): void {\n    this.dialogService.open<string>({\n      title: 'Custom content',\n      component: DialogBodyComponent,\n      data: { message: 'Any component can be the dialog body, with typed data passed in.' },\n    });\n  }\n}",
  ],
  [
    DialogOptionsExample,
    "import { Component, inject } from '@angular/core';\nimport { ButtonComponent, DIALOG_REF, DialogRef, DialogService } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-dialog-body',\n  imports: [ButtonComponent],\n  template: `\n    <p>The dialog's body is a component of your own — it receives DIALOG_REF, so it can close.</p>\n    <gog-button size=\"sm\" (gogClick)=\"ref.close()\">Close from the body</gog-button>\n  `,\n})\nexport class DialogOptionsBodyComponent {\n  protected readonly ref = inject<DialogRef<void>>(DIALOG_REF);\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  template: `\n    <gog-button (gogClick)=\"openNonClosable()\">Not closable</gog-button>\n    <gog-button variant=\"outline\" (gogClick)=\"openNonModal()\">Non-modal</gog-button>\n    <gog-button variant=\"outline\" (gogClick)=\"openWide()\">Custom width</gog-button>\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-wrap: wrap;\n      gap: 12px;\n    }\n  `,\n})\nexport class DialogOptionsExample {\n  private readonly dialogService = inject(DialogService);\n\n  // No header close button, and Escape and backdrop clicks are ignored: the only way out is a\n  // control you render yourself. For a decision the user must actually make.\n  protected openNonClosable(): void {\n    this.dialogService.open({\n      title: 'Confirm before closing',\n      component: DialogOptionsBodyComponent,\n      closable: false,\n    });\n  }\n\n  // No backdrop and no focus trap — the page behind stays usable.\n  protected openNonModal(): void {\n    this.dialogService.open({\n      title: 'Non-modal',\n      component: DialogOptionsBodyComponent,\n      modal: false,\n    });\n  }\n\n  protected openWide(): void {\n    this.dialogService.open({\n      title: 'Wide dialog',\n      component: DialogOptionsBodyComponent,\n      width: '720px',\n    });\n  }\n}",
  ],
  [
    DialogOverviewExample,
    "import { Component, inject, signal } from '@angular/core';\nimport {\n  ButtonComponent,\n  ConfirmationDialogComponent,\n  DialogService,\n  type ConfirmDialogData,\n} from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  template: `\n    <gog-button (gogClick)=\"openConfirm()\">Delete workspace</gog-button>\n    <p class=\"readout\">Last result: {{ lastResult() }}</p>\n    <!-- <gog-dialog /> is mounted once at the root of the app, not here — see the import\n         snippet above. This page mounts it in its own root component, and the StackBlitz\n         project this example opens in does the same. -->\n  `,\n  styles: `\n    :host {\n      display: flex;\n      flex-direction: column;\n      align-items: flex-start;\n      gap: 12px;\n    }\n    .readout {\n      margin: 0;\n      color: var(--gog-muted-text-color);\n      font-size: 0.9em;\n    }\n  `,\n})\nexport class DialogOverviewExample {\n  private readonly dialogService = inject(DialogService);\n\n  protected readonly lastResult = signal('Nothing yet.');\n\n  protected async openConfirm(): Promise<void> {\n    const handle = this.dialogService.open<boolean>({\n      title: 'Delete workspace?',\n      component: ConfirmationDialogComponent,\n      role: 'alertdialog',\n      data: {\n        title: 'Delete workspace?',\n        description: 'This action cannot be undone.',\n        confirmText: 'Delete',\n        cancelText: 'Cancel',\n      } satisfies ConfirmDialogData,\n    });\n\n    // `afterClosed` resolves with whatever the dialog closed with — `undefined` when it was\n    // dismissed by Escape or a backdrop click rather than by one of its own buttons.\n    const confirmed = await handle.afterClosed;\n    this.lastResult.set(confirmed ? 'Confirmed' : 'Cancelled');\n  }\n}",
  ],
  [
    DialogStackedExample,
    "import { Component, inject } from '@angular/core';\nimport {\n  ButtonComponent,\n  DIALOG_DATA,\n  DIALOG_REF,\n  DialogRef,\n  DialogService,\n} from '@guildofgleks/ui';\n\ninterface StackedData {\n  readonly message: string;\n}\n\n@Component({\n  selector: 'app-stacked-body',\n  imports: [ButtonComponent],\n  template: `\n    <p>{{ data.message }}</p>\n    <gog-button size=\"sm\" (gogClick)=\"openAnother()\">Open another on top</gog-button>\n    <gog-button size=\"sm\" variant=\"outline\" (gogClick)=\"ref.close()\">Close</gog-button>\n  `,\n})\nexport class StackedBodyComponent {\n  private readonly dialogService = inject(DialogService);\n  protected readonly data = inject<StackedData>(DIALOG_DATA);\n  protected readonly ref = inject<DialogRef<void>>(DIALOG_REF);\n\n  // The body is an ordinary component, so it can inject DialogService and open another.\n  protected openAnother(): void {\n    this.dialogService.open({\n      title: 'Stacked dialog',\n      component: StackedBodyComponent,\n      data: { message: 'Each open() call stacks on top with an increasing z-index.' },\n    });\n  }\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent],\n  template: `<gog-button (gogClick)=\"open()\">Open the first one</gog-button>`,\n  styles: `\n    :host {\n      display: flex;\n      flex-wrap: wrap;\n      align-items: center;\n      gap: 12px;\n    }\n  `,\n})\nexport class DialogStackedExample {\n  private readonly dialogService = inject(DialogService);\n\n  protected open(): void {\n    this.dialogService.open({\n      title: 'Stacked dialog',\n      component: StackedBodyComponent,\n      data: { message: 'Open another from inside this one — they stack.' },\n    });\n  }\n}",
  ],
]);
