import { CalendarComponent, DatepickerComponent } from '@guildofgleks/ui/datepicker';

import type { DocApi } from '../../doc/doc-api';

export const DATEPICKER_API: readonly DocApi[] = [
  {
    type: DatepickerComponent,
    inputs: [
      { name: 'label', type: 'string', default: "''" },
      { name: 'ariaLabel', type: 'string', default: "''" },
      { name: 'placeholder', type: 'string', default: "''" },
      { name: 'inputId', type: 'string', default: "''" },
      { name: 'value', type: 'GogDatepickerValue (model)', default: 'null' },
      { name: 'selectionMode', type: 'GogDateSelectionMode', default: "'single'" },
      { name: 'min', type: 'Date | null', default: 'null' },
      { name: 'max', type: 'Date | null', default: 'null' },
      { name: 'disabledDates', type: '((date: Date) => boolean) | null', default: 'null' },
      { name: 'defaultMonth', type: 'Date | null', default: 'null' },
      { name: 'numberOfMonths', type: 'number', default: '1' },
      { name: 'showTime', type: 'boolean', default: 'false' },
      { name: 'hourFormat', type: 'GogHourFormat', default: "'24'" },
      { name: 'minuteStep', type: 'number', default: '1' },
      { name: 'showSeconds', type: 'boolean', default: 'false' },
      { name: 'showTodayButton', type: 'boolean', default: 'true' },
      { name: 'showThisMonthButton', type: 'boolean', default: 'false' },
      {
        name: 'todayLabel',
        type: 'string | undefined',
        default: "'Today'",
        config: 'GOG_CONFIG.labels.today',
      },
      {
        name: 'thisMonthLabel',
        type: 'string | undefined',
        default: "'This month'",
        config: 'GOG_CONFIG.labels.thisMonth',
      },
      {
        name: 'format',
        type: 'string | null',
        default: "'dd.MM.yyyy', or 'dd.MM.yyyy HH:mm' with showTime",
        config: 'GOG_CONFIG.datepicker.format',
      },
      {
        name: 'locale',
        type: 'string | undefined',
        default: "'en-US'",
        config: 'GOG_CONFIG.datepicker.locale',
      },
      {
        name: 'firstDayOfWeek',
        type: 'number | undefined',
        default: "the locale's own",
        config: 'GOG_CONFIG.datepicker.firstDayOfWeek',
      },
      { name: 'allowTextInput', type: 'boolean', default: 'true' },
      { name: 'inline', type: 'boolean', default: 'false' },
      {
        name: 'clearable',
        type: 'boolean | undefined',
        default: 'false',
        config: 'GOG_CONFIG.control.clearable',
      },
      {
        name: 'clearAriaLabel',
        type: 'string | undefined',
        default: "'Clear date'",
        config: 'GOG_CONFIG.labels.clearDate',
      },
      {
        name: 'openCalendarLabel',
        type: 'string | undefined',
        default: "'Open calendar'",
        config: 'GOG_CONFIG.labels.openCalendar',
      },
      { name: 'errorMessage', type: 'string', default: "''" },
      {
        name: 'errorDisplay',
        type: 'GogErrorDisplay | undefined',
        default: "'manual'",
        config: 'GOG_CONFIG.control.errorDisplay',
      },
      { name: 'disabled', type: 'boolean', default: 'false' },
      {
        name: 'size',
        type: 'GogSize | undefined',
        default: "'md'",
        config: 'GOG_CONFIG.control.size',
      },
      { name: 'fullWidth', type: 'boolean', default: 'true' },
      {
        name: 'floatLabel',
        type: 'GogFloatLabelVariant | undefined',
        default: "'none'",
        config: 'GOG_CONFIG.floatLabel.variant',
      },
      {
        name: 'floatLabelShowPlaceholder',
        type: 'boolean | undefined',
        default: 'false',
        config: 'GOG_CONFIG.floatLabel.showPlaceholder',
      },
      {
        name: 'appendToBody',
        type: 'boolean | undefined',
        default: 'false',
        config: 'GOG_CONFIG.dropdown.appendToBody',
      },
      {
        name: 'dropdownDirection',
        type: 'GogDropdownDirection | undefined',
        default: "'auto'",
        config: 'GOG_CONFIG.dropdown.direction',
      },
      { name: 'dropdownZIndex', type: 'number | null', default: 'null' },
    ],
    outputs: [{ name: 'valueChange', payload: 'GogDatepickerValue' }],
  },
  {
    type: CalendarComponent,
    inputs: [
      { name: 'value', type: 'GogDatepickerValue (model)', default: 'null' },
      { name: 'selectionMode', type: 'GogDateSelectionMode', default: "'single'" },
      { name: 'min', type: 'Date | null', default: 'null' },
      { name: 'max', type: 'Date | null', default: 'null' },
      { name: 'disabledDates', type: '((date: Date) => boolean) | null', default: 'null' },
      { name: 'defaultMonth', type: 'Date | null', default: 'null' },
      { name: 'numberOfMonths', type: 'number', default: '1' },
      { name: 'showTime', type: 'boolean', default: 'false' },
      { name: 'hourFormat', type: 'GogHourFormat', default: "'24'" },
      { name: 'minuteStep', type: 'number', default: '1' },
      { name: 'showSeconds', type: 'boolean', default: 'false' },
      { name: 'showTodayButton', type: 'boolean', default: 'true' },
      { name: 'showThisMonthButton', type: 'boolean', default: 'false' },
      {
        name: 'locale',
        type: 'string | undefined',
        default: "'en-US'",
        config: 'GOG_CONFIG.datepicker.locale',
      },
      {
        name: 'firstDayOfWeek',
        type: 'number | null | undefined',
        default: "the locale's own",
        config: 'GOG_CONFIG.datepicker.firstDayOfWeek',
      },
      { name: 'size', type: 'GogSize', default: "'md'" },
      {
        name: 'todayLabel',
        type: 'string | undefined',
        default: "'Today'",
        config: 'GOG_CONFIG.labels.today',
      },
      {
        name: 'thisMonthLabel',
        type: 'string | undefined',
        default: "'This month'",
        config: 'GOG_CONFIG.labels.thisMonth',
      },
      {
        name: 'previousMonthLabel',
        type: 'string | undefined',
        default: "'Previous month'",
        config: 'GOG_CONFIG.labels.previousMonth',
      },
      {
        name: 'nextMonthLabel',
        type: 'string | undefined',
        default: "'Next month'",
        config: 'GOG_CONFIG.labels.nextMonth',
      },
      {
        name: 'previousYearLabel',
        type: 'string | undefined',
        default: "'Previous year'",
        config: 'GOG_CONFIG.labels.previousYear',
      },
      {
        name: 'nextYearLabel',
        type: 'string | undefined',
        default: "'Next year'",
        config: 'GOG_CONFIG.labels.nextYear',
      },
      {
        name: 'hoursLabel',
        type: 'string | undefined',
        default: "'Hours'",
        config: 'GOG_CONFIG.labels.hours',
      },
      {
        name: 'minutesLabel',
        type: 'string | undefined',
        default: "'Minutes'",
        config: 'GOG_CONFIG.labels.minutes',
      },
      {
        name: 'secondsLabel',
        type: 'string | undefined',
        default: "'Seconds'",
        config: 'GOG_CONFIG.labels.seconds',
      },
    ],
    outputs: [
      { name: 'valueChange', payload: 'GogDatepickerValue' },
      { name: 'gogDateSelect', payload: 'GogDatepickerValue (a complete selection only)' },
    ],
  },
];
