// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const BREADCRUMBS_EXAMPLES = {
  breadcrumbsCollapse: {
    html: '<div>\n  <span>maxItems unset</span>\n  <gog-breadcrumbs>\n    @for (crumb of trail; track crumb; let last = $last) {\n      @if (last) {\n        <span *gogBreadcrumb>{{ crumb }}</span>\n      } @else {\n        <a *gogBreadcrumb routerLink="/components/breadcrumbs">{{ crumb }}</a>\n      }\n    }\n  </gog-breadcrumbs>\n</div>\n<div>\n  <span>[maxItems]="4"</span>\n  <gog-breadcrumbs [maxItems]="4">\n    @for (crumb of trail; track crumb; let last = $last) {\n      @if (last) {\n        <span *gogBreadcrumb>{{ crumb }}</span>\n      } @else {\n        <a *gogBreadcrumb routerLink="/components/breadcrumbs">{{ crumb }}</a>\n      }\n    }\n  </gog-breadcrumbs>\n</div>\n<div>\n  <span>itemsBefore 2, after 1</span>\n  <gog-breadcrumbs [maxItems]="4" [itemsBefore]="2" [itemsAfter]="1">\n    @for (crumb of trail; track crumb; let last = $last) {\n      @if (last) {\n        <span *gogBreadcrumb>{{ crumb }}</span>\n      } @else {\n        <a *gogBreadcrumb routerLink="/components/breadcrumbs">{{ crumb }}</a>\n      }\n    }\n  </gog-breadcrumbs>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsCollapseExample {\n  protected readonly trail = ['Workspace', 'Sales', 'Europe', 'Germany', 'Berlin', 'Q3 orders'];\n}",
  },
  breadcrumbsNarrow: {
    html: '<div style="max-width: 16rem">\n  <gog-breadcrumbs>\n    @for (crumb of trail; track crumb; let last = $last) {\n      @if (last) {\n        <span *gogBreadcrumb>{{ crumb }}</span>\n      } @else {\n        <a *gogBreadcrumb routerLink="/components/breadcrumbs">{{ crumb }}</a>\n      }\n    }\n  </gog-breadcrumbs>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsNarrowExample {\n  protected readonly trail = ['Workspace', 'Sales', 'Europe', 'Germany', 'Berlin', 'Q3 orders'];\n}",
  },
  breadcrumbsOverview: {
    html: '<gog-breadcrumbs>\n  <a *gogBreadcrumb routerLink="/">Home</a>\n  <a *gogBreadcrumb routerLink="/components/breadcrumbs">Components</a>\n  <span *gogBreadcrumb>Breadcrumbs</span>\n</gog-breadcrumbs>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsOverviewExample {}",
  },
  breadcrumbsRtl: {
    html: '<div dir="rtl">\n  <gog-breadcrumbs>\n    <a *gogBreadcrumb routerLink="/">Home</a>\n    <a *gogBreadcrumb routerLink="/general/getting-started">Docs</a>\n    <span *gogBreadcrumb>Install</span>\n  </gog-breadcrumbs>\n</div>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsRtlExample {}",
  },
  breadcrumbsSeparator: {
    html: '<gog-breadcrumbs separatorIcon="arrow-right">\n  <a *gogBreadcrumb routerLink="/">Home</a>\n  <a *gogBreadcrumb routerLink="/general/getting-started">Docs</a>\n  <span *gogBreadcrumb>Install</span>\n</gog-breadcrumbs>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsSeparatorExample {}",
  },
  breadcrumbsSizes: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>{{ size }}</span>\n    <gog-breadcrumbs [size]="size">\n      <a *gogBreadcrumb routerLink="/">Home</a>\n      <a *gogBreadcrumb routerLink="/components/breadcrumbs">Components</a>\n      <span *gogBreadcrumb>Breadcrumbs</span>\n    </gog-breadcrumbs>\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { RouterLink } from '@angular/router';\nimport { BreadcrumbsComponent, GogBreadcrumbDirective, type GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [BreadcrumbsComponent, GogBreadcrumbDirective, RouterLink],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class BreadcrumbsSizesExample {\n  protected readonly sizes: readonly GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
  },
} as const satisfies Record<string, ExampleSource>;
