// GENERATED by scripts/generate-example-sources.mjs from the example folders beside this
// file — do not edit by hand. Run `npm run generate:examples` after changing an example.
import type { ExampleSource } from '../../components/shared/example-source';

export const CHIP_EXAMPLES = {
  chipConfig: {
    html: '<gog-chip>Ripple from the config</gog-chip>\n<gog-chip [ripple]="false">[ripple]="false" — the instance wins</gog-chip>\n<!-- A label never ripples, whatever the config says. -->\n<gog-chip [clickable]="false">Not clickable</gog-chip>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ChipComponent, provideGogConfig } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  // Usually in app.config.ts; here on the component, so it reaches only its own chips.\n  providers: [provideGogConfig({ ripple: { enabled: true } })],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipConfigExample {}",
    css: '',
  },
  chipContent: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>size: {{ size }}</span>\n    <gog-chip [size]="size" [avatarUrl]="ada" avatarAlt="">Ada Lovelace</gog-chip>\n    <gog-chip [size]="size" iconName="star">Starred</gog-chip>\n    <!-- Avatar and icon are independent: set both and both render. -->\n    <gog-chip\n      [size]="size"\n      [avatarUrl]="alan"\n      avatarAlt=""\n      iconName="warning"\n      removable\n      removeAriaLabel="Remove Alan Turing"\n    >\n      Alan Turing\n    </gog-chip>\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ChipComponent, GogSize } from '@guildofgleks/ui';\n\n/** An initials avatar as a data URL, so the example needs no image files. */\nfunction avatar(initials: string, fill: string): string {\n  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect width='64' height='64' fill='${fill}'/><text x='32' y='40' text-anchor='middle' font-size='26' font-family='Arial' fill='%231a1208'>${initials}</text></svg>`;\n  return `data:image/svg+xml;utf8,${svg}`;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipContentExample {\n  protected readonly sizes: GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n  protected readonly ada = avatar('AL', '%23c9b896');\n  protected readonly alan = avatar('AT', '%23d4b483');\n}",
    css: '',
  },
  chipFilter: {
    html: "<!-- Two-way: each chip flips its own value on click, Enter and Space. -->\n@for (topic of topics; track topic.label) {\n  <gog-chip [(selected)]=\"topic.on\">{{ topic.label }}</gog-chip>\n}\n\n<p>selected: {{ selectedTopics().join(', ') || 'none' }}</p>",
    ts: "import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';\nimport { ChipComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipFilterExample {\n  protected readonly topics = [\n    { label: 'Accessibility', on: signal<boolean | null>(true) },\n    { label: 'Theming', on: signal<boolean | null>(false) },\n    { label: 'Forms', on: signal<boolean | null>(true) },\n    { label: 'Tables', on: signal<boolean | null>(false) },\n  ];\n  protected readonly selectedTopics = computed(() =>\n    this.topics.filter((topic) => topic.on()).map((topic) => topic.label),\n  );\n}",
    css: '',
  },
  chipOverview: {
    html: '<gog-chip (gogClick)="lastClicked.set(\'Design\')">Design</gog-chip>\n<gog-chip (gogClick)="lastClicked.set(\'Research\')">Research</gog-chip>\n\n<p>gogClick: {{ lastClicked() }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ChipComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipOverviewExample {\n  protected readonly lastClicked = signal('nothing yet');\n}",
    css: '',
  },
  chipRemovable: {
    html: '<!-- The chip does not remove itself: the list it came from does. -->\n@for (filter of filters(); track filter) {\n  <gog-chip\n    [clickable]="false"\n    removable\n    [removeAriaLabel]="\'Remove filter \' + filter"\n    (gogRemove)="remove(filter)"\n  >\n    {{ filter }}\n  </gog-chip>\n}\n<gog-chip [clickable]="false" removable disabled>Disabled hides the button</gog-chip>\n<gog-button variant="outline" size="sm" (gogClick)="reset()">Reset</gog-button>\n\n<p>last: {{ lastAction() }}</p>',
    ts: "import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ButtonComponent, ChipComponent } from '@guildofgleks/ui';\n\nconst FILTERS = ['Angular', 'Design system', 'Pinned', 'Open'];\n\n@Component({\n  selector: 'app-example',\n  imports: [ButtonComponent, ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipRemovableExample {\n  protected readonly filters = signal(FILTERS);\n  protected readonly lastAction = signal('nothing yet');\n\n  protected remove(label: string): void {\n    this.filters.update((filters) => filters.filter((filter) => filter !== label));\n    this.lastAction.set(`gogRemove: ${label}`);\n  }\n\n  protected reset(): void {\n    this.filters.set(FILTERS);\n    this.lastAction.set('reset');\n  }\n}",
    css: '',
  },
  chipShapes: {
    html: '@for (shape of shapes; track shape) {\n  <gog-chip [shape]="shape">shape="{{ shape }}"</gog-chip>\n  <gog-chip [shape]="shape" [avatarUrl]="ada" avatarAlt="" removable>Ada Lovelace</gog-chip>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ChipComponent } from '@guildofgleks/ui';\n\n/** An initials avatar as a data URL, so the example needs no image files. */\nfunction avatar(initials: string, fill: string): string {\n  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect width='64' height='64' fill='${fill}'/><text x='32' y='40' text-anchor='middle' font-size='26' font-family='Arial' fill='%231a1208'>${initials}</text></svg>`;\n  return `data:image/svg+xml;utf8,${svg}`;\n}\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipShapesExample {\n  protected readonly shapes = ['rounded', 'pill'] as const;\n  protected readonly ada = avatar('AL', '%23c9b896');\n}",
    css: '',
  },
  chipStates: {
    html: '@for (size of sizes; track size) {\n  <div>\n    <span>size: {{ size }}</span>\n    <gog-chip [size]="size">default</gog-chip>\n    <!-- A toggle that is off: it says so with aria-pressed="false". -->\n    <gog-chip [size]="size" [selected]="false">off</gog-chip>\n    <gog-chip [size]="size" [selected]="true">on</gog-chip>\n    <gog-chip [size]="size" disabled>disabled</gog-chip>\n    <!-- On, and unavailable right now: the ring stays. -->\n    <gog-chip [size]="size" [selected]="true" disabled>disabled, on</gog-chip>\n    <gog-chip [size]="size" [clickable]="false">label</gog-chip>\n  </div>\n}',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ChipComponent, GogSize } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipStatesExample {\n  protected readonly sizes: GogSize[] = ['xsm', 'sm', 'md', 'lg', 'slg'];\n}",
    css: '',
  },
  chipWidth: {
    html: '<gog-chip>fullWidth unset</gog-chip>\n<!-- The remove button stays at the end of the stretched chip. -->\n<gog-chip fullWidth removable>fullWidth</gog-chip>',
    ts: "import { ChangeDetectionStrategy, Component } from '@angular/core';\nimport { ChipComponent } from '@guildofgleks/ui';\n\n@Component({\n  selector: 'app-example',\n  imports: [ChipComponent],\n  templateUrl: './example.html',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})\nexport class ChipWidthExample {}",
    css: '',
  },
} as const satisfies Record<string, ExampleSource>;
